spring.application.name=api


#Port API
server.port=8000

#Port ML
ml.base-url=http://localhost:8080
ml.predict-path=/predict/sentiment
ml.timeout-ms=3000

# H2 Database Console (solo laboratorio local)
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.datasource.url=jdbc:h2:file:./data/sentiment_db;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=contrasenia
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
